build:
  image: rikorose/gcc-cmake
  script:
    - echo "running scripts in the build job"
    - cmake -S . -B "build"
    - cmake --build ./build --config Release
  artifacts:
    paths:
      - build/app/EvalCI

pages:
  image: node
  script:
    - cd web 
    - npm install
    - npm run build
    - cd ..
    - cp -r ./web/build public
  artifacts:
    paths:
      - public