.macos_buildcloud_runners:
  image: rikorose/gcc-cmake

stages:
  - build

before_script:
 - echo "started by ${GITLAB_USER_NAME}"

build:
  extends:
    - .macos_buildcloud_runners
  stage: build
  script:
    - echo "running scripts in the build job"
    - cmake -S . -B "build"
    - cmake --build ./build --config Release
  artifacts:
    paths:
      - build/app/EvalCI
