stages:
  - build
  - deploy

web:
  stage: build
  image: node
  variables: 
    PUBLIC_URL: https://cbastuckot.gitlab.io/otstarter/
  script:
    - cd web 
    - npm install
    - npm run build
  artifacts:
    paths:
      - web/build

plugin:
  stage: build
  image: rikorose/gcc-cmake
  script:
    - echo "running scripts in the build job"
    - cmake -S . -B "build-c360"
    - cmake --build ./build-c360 --config Release
  artifacts:
    paths:
      - build-c360/app/EvalCI

pages:
  stage: deploy
  image: alpine:latest
  variables:
    GIT_STRATEGY: none  # do not clone git repo
  script:
    - cp -r web/build public
  artifacts:
    paths:
      - public